### ISSUE TITLE
Alternatives to Goss?

### ISSUE THREAD

**Issue by webcaptcha** [goss-org/goss#891]
Hi, I'm not remembered how I find this awesome tool. It was a few years ago. I'm interesting, is it one of a kind tool or any competitors/alternatives?

**Comment by ripienaar** [comment]
It’s fairly unique. In the same space are serverspec, infrataster, inspect all ruby and in various levels of abandonment

**Comment by aelsabbahy** [comment]
TiL: infrataster, never heard of it before

@ripienaar pretty much covered the major ones.

some others:
* [pytest-testinfra](https://github.com/pytest-dev/pytest-testinfra)
* [container-structure-test](https://github.com/GoogleContainerTools/container-structure-test) - container testing
* [terratest](https://github.com/gruntwork-io/terratest) A bit of a different scope IMO (listing them here since they mention goss in their [docs](https://terratest.gruntwork.io/docs/testing-best-practices/alternative-testing-tools/))
